### ISSUE TITLE
Use of other GPIO Pins

### ISSUE THREAD

**Issue by ChristianH99** [techman83/Filament-Scale-Enhanced#16]
Hi,
is it possible to use other GPIO pins for connecting the load cell? 20 and 21 are already in use for me. Can I simply change the values in __init__.py or are these pins somehow "hardware-required"?

Thanks,
Christian

**Comment by techman83** [comment]
I would expect that any Digital IO pin should be fine. So far I've only really ported the library to Python 3 and added some basic tests and linting.

I'll open a couple of issues relating to this. If you wanted to have a crack at making it configurable, Filament Sensor Simplified has a good interface we could draw inspiration from. It is a little of a pain that we're locked to a pin layout type and specific pins.

**Comment by techman83** [comment]
I've opened a few issues relating to this. Hopefully you got that working, if you feel like taking a shot at adding the functionality I'd happily review/merge new features.
