### ISSUE TITLE
IDEX dual extruder

### ISSUE THREAD

**Issue by EungwanLee** [techman83/Filament-Scale-Enhanced#20]
Hi,
I have a dual extruder printer. Can I install 2 devices on the same raspberry pi to weight 2 spools?

**Comment by techman83** [comment]
Hi @EungwanLee - Currently no. I have raised an enhancement (#22 ), but it would require re-architecting of the plugin to achieve. I'd be happy to provide code guidance and ideas, but I don't have a lot of free time to make big changes at the moment.
