### ISSUE TITLE
compatible with octoprint 1.73

### ISSUE THREAD

**Issue by sneex14** [techman83/Filament-Scale-Enhanced#30]
Hi, can't get it working with 1.73 octoprint version. 1.72 works fine
![scale](https://user-images.githubusercontent.com/98392188/150962424-b91a1a49-efe2-4a61-8374-9a7585222222.PNG)

Lightning says:
Incompatible with Octoprint or the Python environment

**Comment by techman83** [comment]
I assume you're using a manual install or an older octopi image? I can confirm it works on 1.7.3 + Python 3, but when I took over maintenance I dropped support for Python 2.

**Comment by sneex14** [comment]
Oh, i'm sorry. Don't know why, but this one Pi has Python 2 installed. Thanks for the help.

**Comment by techman83** [comment]
That's ok, it was the default for a long time and a lot of Distros still have dependencies on it. OctoPi runs it with python 3 and depending how you installed it, your distro probably has both and you could reinstall with 3 instead of 2. But YMMV
