### ISSUE TITLE
Add MQTT Integration via OctoPrint-MQTT

### ISSUE THREAD

**Issue by montyfert** [techman83/Filament-Scale-Enhanced#39]
hi @techman83 
 is there any way to send mqtt messages so i can connect a screen .
thanks 
martin

**Comment by techman83** [comment]
@montyfert - that's a bit out of scope for this project, but this project looks promising -> https://github.com/OctoPrint/OctoPrint-MQTT

**Comment by montyfert** [comment]
thanks 
martin

**Comment by montyfert** [comment]
hi me again , i asked about the mqtt plugin and was told  (OctoPrint has no such data available to it, so if you are using a plugin for that information you need to request mqtt integration there.)
so please can we have mqtt intergration .
thanks 
martin

**Comment by techman83** [comment]
@montyfert I've added the appropriate labels - I've not had a lot of spare time lately to work with my 3D printer, but I would accept even a rough PR.

**Comment by jcassel** [comment]
@montyfert I just put in a Pull Request (PR) that I think will get you want you want.  @techman83  will have to review and approve it am hoping I did a good enough job that it goes though quick for you.  I was doing this same work on my plug in SIOControl earlier today, so I figured I would just hit this quick too.

**Comment by montyfert** [comment]
thanks so much much apreciated
martin

**Comment by techman83** [comment]
@montyfert / @jcassel - This is a preview build with MQTT support

[Filament Scale Enhanced-0.0.0.zip](https://github.com/techman83/Filament-Scale-Enhanced/files/12326803/Filament.Scale.Enhanced-0.0.0.zip)

**Comment by jcassel** [comment]
Installed and tested. Looks good. @techman83

**Comment by techman83** [comment]
Release shipped! Thanks for testing @jcassel - can't recall how long until the central repo picks up the new release @montyfert
